import mysql.connector
import tkinter.messagebox as messagebox
from tkinter import*
conn=mysql.connector.connect(host="localhost",user="root",passwd="",database="fasal")
cur=conn.cursor()
def save():
    regno=t1.get()
    name=t2.get()
    mark1=t3.get()
    mark2=t4.get()
    mark3=t5.get()
    if regno=='' or name=='' or mark1=='' or mark2=='' or mark3=='':
        messagebox.showinfo("Insert Status","Please fill all the fields")
    else:
        cur.execute("INSERT INTO register VALUE('%s','%s',%s,%s,%s)"%(regno,name,mark1,mark2,mark3))
        conn.commit()
        t1.delete(0,END)
        t2.delete(0,END)
        t3.delete(0,END)
        t4.delete(0,END)
        t5.delete(0,END)
        messagebox.showinfo("Insert status","registration saved successfully")
def show():
    regno=t1.get()
    name=t2.get()
    mark1=t3.get()
    mark2=t4.get()
    mark3=t5.get()
    if regno=='':
        messagebox.showinfo("Insert status","please type your register number")
    else:
        cur.execute("select *from register where regno='%s'"%regno)
        result=cur.fetchall()
        for a in result:
            t2.insert(0,a[1])
            t3.insert(0,a[2])
            t4.insert(0,a[3])
            t5.insert(0,a[4])
def delete():
    regno=t1.get()
    name=t2.get()
    mark1=t3.get()
    mark2=t4.get()
    mark3=t5.get()
    if regno=='':
        messagebox.showinfo("Insert status","please type your register number")
    else:
        cur.execute("delete from register where regno='%s'"%regno)
        messagebox.showinfo("insert status","Deleted successfully")
        conn.commit()
        t1.delete(0,END)
def update():
    regno=t1.get()
    name=t2.get()
    mark1=t3.get()
    mark2=t4.get()
    mark3=t5.get()
    if regno=='':
        messagebox.showinfo("Insert status","please type your register number")
    else:
        cur.execute("update register set name='%s', mark1=%s, mark2=%s, mark3=%s where regno='%s'"%(name, mark1, mark2, mark3, regno))
        messagebox.showinfo("Insert status","updated successfully")
        conn.commit()
        t1.delete(0,END)
        t2.delete(0,END)
        t3.delete(0,END)
        t4.delete(0,END)
        t5.delete(0,END)
def clear():
        t1.delete(0,END)
        t2.delete(0,END)
        t3.delete(0,END)
        t4.delete(0,END)
        t5.delete(0,END)
root=Tk()
root.title("Register")
root.geometry("500x500")
root.configure(background="skyblue")
lbl1=Label(root,text="Reg number",background="skyblue")
lbl1.place(x=30,y=30)
t1=Entry(root)
t1.place(x=120,y=30)
lbl2=Label(root,text="Name",background="skyblue")
lbl2.place(x=30,y=60)
t2=Entry(root)
t2.place(x=120,y=60)
lbl3=Label(root,text="Mark 1",background="skyblue")
lbl3.place(x=30,y=90)
t3=Entry(root)
t3.place(x=120,y=90)
lbl4=Label(root,text="Mark 2",background="skyblue")
lbl4.place(x=30,y=120)
t4=Entry(root)
t4.place(x=120,y=120)
lbl5=Label(root,text="Mark 3",background="skyblue")
lbl5.place(x=30,y=150)
t5=Entry(root)
t5.place(x=120,y=150)
btn1=Button(root,text="Save",command=save)
btn1.place(x=255,y=30)
btn2=Button(root,text="Show",command=show)
btn2.place(x=255,y=60)
btn3=Button(root,text="Delete",command=delete)
btn3.place(x=255,y=90)
btn4=Button(root,text="Update",command=update)
btn4.place(x=255,y=120)
btn5=Button(root,text="Clear",command=clear)
btn5.place(x=255,y=150)
root.mainloop()